### ISSUE TITLE
Solution Throws Exceptions

### ISSUE THREAD

**Issue by SamuelAsherRivello** [adammyhre/Unity-Serialized-Interface#2]
The provided solution throws exceptions when using the latest LTS of Unity 6 (as of this post), with assembly definitions, and namespaces in a new project.

Please add a Unity project with 1) one demo scene to your repo that demonstrates proper use of your solution once you have it 2) with assembly definitions and namespaces, 3) working without errors.

![2024-11-05_13-46-38](https://github.com/user-attachments/assets/b1528457-a87f-452a-947a-aea4910c65e1)

**Comment by adammyhre** [comment]
From the exceptions being thrown, it appears that you are attempting to assign or use types that don’t derive from UnityEngine.Object, which Unity’s serialization system doesn’t support directly. Unity’s SerializedProperty.objectReferenceValue only accepts references to objects inheriting from UnityEngine.Object, like GameObject, Component, or other Unity asset types.

But, without actual steps to reproduce, it's only possible to guess what you are trying to do that causes this.

**Comment by adammyhre** [comment]
I see the original issue has been edited to mention the issue happens when using assembly definition file(s).  However, even in a project with multiple asmdef files where one class must reference an interface and classes from another assembly, there are still no errors.

If no steps to reproduce are provided, this issue will be closed.
